// Auto-generated by scripts/generate-version.js - DO NOT EDIT
// Generated at: 2026-01-25T14:01:04.449Z
// Source: package.json v0.1.0

export const VERSION = '0.1.0';
export const BUILD_TIME = '2026-01-25T14:01:04.449Z';
export const GIT_COMMIT = '71fb6e7f-dirty';
export const GIT_BRANCH = 'main';

// Build info object
export const BUILD_INFO = {
  version: VERSION,
  buildTime: BUILD_TIME,
  gitCommit: GIT_COMMIT,
  gitBranch: GIT_BRANCH,
  gitDirty: true,
} as const;
