#!/usr/bin/env node
/**
 * Generate version.ts file from package.json with build timestamp and git info
 *
 * This ensures SSOT (Single Source of Truth) for version information:
 * - Version comes from package.json
 * - Build time is set at build time (not runtime)
 * - Git commit hash from git CLI
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Paths
const ROOT = path.join(__dirname, '..');
const UI_DIR = path.join(ROOT, 'keyrx_ui');
const PACKAGE_JSON = path.join(UI_DIR, 'package.json');
const VERSION_TS = path.join(UI_DIR, 'src', 'version.ts');
const CARGO_TOML = path.join(ROOT, 'Cargo.toml');

// Read package.json
const packageJson = JSON.parse(fs.readFileSync(PACKAGE_JSON, 'utf8'));
const version = packageJson.version;

// Get git commit hash (short)
let gitCommit = 'unknown';
try {
  gitCommit = execSync('git rev-parse --short HEAD', {
    cwd: ROOT,
    encoding: 'utf8'
  }).trim();
} catch (e) {
  console.warn('Warning: Could not get git commit hash:', e.message);
}

// Get git branch
let gitBranch = 'unknown';
try {
  gitBranch = execSync('git rev-parse --abbrev-ref HEAD', {
    cwd: ROOT,
    encoding: 'utf8'
  }).trim();
} catch (e) {
  console.warn('Warning: Could not get git branch:', e.message);
}

// Check if working directory is clean
let gitDirty = false;
try {
  const status = execSync('git status --porcelain', {
    cwd: ROOT,
    encoding: 'utf8'
  });
  gitDirty = status.trim().length > 0;
} catch (e) {
  console.warn('Warning: Could not check git status:', e.message);
}

// Build timestamp (ISO 8601)
const buildTime = new Date().toISOString();

// Verify version matches Cargo.toml
const cargoToml = fs.readFileSync(CARGO_TOML, 'utf8');
const cargoVersionMatch = cargoToml.match(/^version\s*=\s*"([^"]+)"/m);
const cargoVersion = cargoVersionMatch ? cargoVersionMatch[1] : null;

if (cargoVersion && cargoVersion !== version) {
  console.warn(`⚠️  Version mismatch!`);
  console.warn(`   Cargo.toml: ${cargoVersion}`);
  console.warn(`   package.json: ${version}`);
  console.warn(`   Please sync versions manually or run: npm run sync-version`);
}

// Generate version.ts content
const content = `// Auto-generated by scripts/generate-version.js - DO NOT EDIT
// Generated at: ${buildTime}
// Source: package.json v${version}

export const VERSION = '${version}';
export const BUILD_TIME = '${buildTime}';
export const GIT_COMMIT = '${gitCommit}${gitDirty ? '-dirty' : ''}';
export const GIT_BRANCH = '${gitBranch}';

// Build info object
export const BUILD_INFO = {
  version: VERSION,
  buildTime: BUILD_TIME,
  gitCommit: GIT_COMMIT,
  gitBranch: GIT_BRANCH,
  gitDirty: ${gitDirty},
} as const;
`;

// Write file
fs.writeFileSync(VERSION_TS, content, 'utf8');

console.log('✓ Generated version.ts:');
console.log(`  Version: ${version}`);
console.log(`  Build Time: ${buildTime}`);
console.log(`  Git: ${gitCommit} (${gitBranch})${gitDirty ? ' [dirty]' : ''}`);
if (cargoVersion) {
  console.log(`  Cargo version: ${cargoVersion} ${cargoVersion === version ? '✓' : '✗'}`);
}
