/*
 Generated by typeshare 1.13.4
*/

/** Activation result returned by activate_profile */
export interface ActivationRpcResult {
	success: boolean;
	compile_time_ms: number;
	reload_time_ms: number;
	error?: string;
}

/** Current daemon state snapshot. */
export interface DaemonState {
	/** Active modifier IDs (e.g., ["MD_00", "MD_01"]). */
	modifiers: string[];
	/** Active lock IDs (e.g., ["LK_00"]). */
	locks: string[];
	/** Current active layer name. */
	layer: string;
	/** Currently active profile name (if any). */
	active_profile?: string;
}

/** Device metadata entry */
export interface DeviceEntry {
	/** Unique device identifier (max 256 chars) */
	id: string;
	/** User-friendly name (max 64 chars) */
	name: string;
	/** Serial number if available */
	serial?: string;
	/** Associated layout name (max 32 chars) */
	layout?: string;
	/** Last seen timestamp (Unix seconds) */
	last_seen: number;
}

/** Device information returned by RPC methods */
export interface DeviceRpcInfo {
	id: string;
	name: string;
	path: string;
	serial?: string;
	active: boolean;
	layout?: string;
}

/** Event in event log */
export interface EventRpcEntry {
	timestamp: number;
	key_code: number;
	event_type: string;
	device_id: string;
}

/** Individual key event data. */
export interface KeyEventData {
	/** Timestamp in microseconds since UNIX epoch. */
	timestamp: number;
	/** Key code (e.g., "KEY_A"). */
	keyCode: string;
	/** Event type ("press" or "release"). */
	eventType: string;
	/** Input key (before mapping). */
	input: string;
	/** Output key (after mapping). */
	output: string;
	/** Processing latency in microseconds. */
	latency: number;
	/** Device ID (unique identifier for the source device). */
	deviceId?: string;
	/** Device name (human-readable name). */
	deviceName?: string;
	/** Mapping type applied (e.g., "simple", "tap_hold", "layer_switch"). */
	mappingType?: string;
	/** Whether a mapping was triggered for this event. */
	mappingTriggered: boolean;
}

/** Latency statistics returned by get_latency */
export interface LatencyRpcStats {
	min_us: number;
	avg_us: number;
	max_us: number;
	p50_us: number;
	p95_us: number;
	p99_us: number;
	count: number;
}

/** Latency statistics. */
export interface LatencyStats {
	/** Minimum latency in microseconds. */
	min: number;
	/** Average latency in microseconds. */
	avg: number;
	/** Maximum latency in microseconds. */
	max: number;
	/** 95th percentile latency in microseconds. */
	p95: number;
	/** 99th percentile latency in microseconds. */
	p99: number;
	/** Timestamp of this stats snapshot (microseconds since UNIX epoch). */
	timestamp: number;
}

/** Profile configuration returned by get_profile_config */
export interface ProfileConfigRpc {
	name: string;
	source: string;
}

/** Profile information returned by RPC methods */
export interface ProfileRpcInfo {
	name: string;
	layer_count: number;
	active: boolean;
	modified_at_secs: number;
}

/** Result of restart_daemon command */
export interface RestartResult {
	success: boolean;
	message: string;
}

/** RPC error structure following JSON-RPC 2.0 conventions */
export interface RpcError {
	/** Numeric error code */
	code: number;
	/** Human-readable error message */
	message: string;
	/** Optional additional error data */
	data: any;
}

/** Messages sent from client to server */
export type ClientMessage = 
	/** Query request - read-only operation that returns data */
	| { type: "query", content: {
	/** Unique identifier for request/response correlation */
	id: string;
	/** Method name to invoke */
	method: string;
	/** Optional parameters for the method */
	params?: any;
}}
	/** Command request - operation that modifies state */
	| { type: "command", content: {
	/** Unique identifier for request/response correlation */
	id: string;
	/** Method name to invoke */
	method: string;
	/** Optional parameters for the method */
	params?: any;
}}
	/** Subscribe to a channel for real-time updates */
	| { type: "subscribe", content: {
	/** Unique identifier for request/response correlation */
	id: string;
	/** Channel name to subscribe to */
	channel: string;
}}
	/** Unsubscribe from a channel */
	| { type: "unsubscribe", content: {
	/** Unique identifier for request/response correlation */
	id: string;
	/** Channel name to unsubscribe from */
	channel: string;
}};

/** Events broadcast from the daemon to WebSocket clients. */
export type DaemonEvent = 
	/** Current daemon state (modifiers, locks, layer). */
	| { type: "state", payload: DaemonState }
	/** Individual key event (press/release). */
	| { type: "event", payload: KeyEventData }
	/** Latency statistics update. */
	| { type: "latency", payload: LatencyStats };

/** Messages sent from server to client */
export type ServerMessage = 
	/** Response to a query or command */
	| { type: "response", content: {
	/** Request ID this response corresponds to */
	id: string;
	/** Result data (success) or None if error */
	result: any;
	/** Error information (failure) or None if success */
	error?: RpcError;
}}
	/** Event broadcast to subscribed clients */
	| { type: "event", content: {
	/** Channel this event was published on */
	channel: string;
	/** Event data */
	data: any;
}}
	/** Initial handshake message sent on connection */
	| { type: "connected", content: {
	/** Protocol version */
	version: string;
	/** Server timestamp in microseconds */
	timestamp: number;
}};

