import React, { useState, useMemo, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { ProfileCard } from '../components/ProfileCard';
import { Button } from '../components/Button';
import { Modal } from '../components/Modal';
import { Input } from '../components/Input';
import { Plus, CheckCircle, AlertCircle } from 'lucide-react';
import { SkeletonCard } from '../components/LoadingSkeleton';
import {
  useProfiles,
  useCreateProfile,
  useActivateProfile,
  useDeleteProfile,
  useUpdateProfile,
} from '../hooks/useProfiles';
import { getErrorMessage } from '../utils/errorUtils';

interface Profile {
  id: string;
  name: string;
  description?: string;
  isActive: boolean;
  lastModified: string;
  rhaiPath?: string;
  fileExists?: boolean;
}

/**
 * ProfilesPage Component
 *
 * Profile management interface showing:
 * - Grid of profile cards (responsive: 3 cols desktop, 2 cols tablet, 1 col mobile)
 * - Create new profile button
 * - Activate/Edit/Delete actions per profile
 * - Active profile highlighted with green checkmark and border
 *
 * User Flows:
 * - Create: Click "Create Profile" → Modal opens → Enter name/description → Save
 * - Activate: Click "Activate" on inactive profile → Becomes active, previous deactivates
 * - Edit: Click "Edit" → Modal opens with current values → Update
 * - Delete: Click "Delete" → Confirmation modal → Confirm → Profile removed
 *
 * Requirements: Req 6 (Profile Management User Flow)
 */
export const ProfilesPage: React.FC = () => {
  const navigate = useNavigate();

  // Fetch profiles from real API
  const { data: profilesData, isLoading, error } = useProfiles();
  const createProfileMutation = useCreateProfile();
  const activateProfileMutation = useActivateProfile();
  const deleteProfileMutation = useDeleteProfile();
  const updateProfileMutation = useUpdateProfile();

  // Transform API data to component format
  const profiles: Profile[] = useMemo(() => {
    if (!profilesData) return [];

    return profilesData.map((p) => ({
      id: p.name, // Use name as ID since it's unique
      name: p.name,
      description: undefined, // API doesn't provide description yet
      isActive: p.isActive,
      lastModified: new Date(p.modifiedAt).toLocaleString('en-CA', {
        year: 'numeric',
        month: '2-digit',
        day: '2-digit',
        hour: '2-digit',
        minute: '2-digit',
        hour12: false,
      }),
      rhaiPath: p.rhaiPath,
      fileExists: true, // Assume file exists if returned by API
    }));
  }, [profilesData]);

  const [createModalOpen, setCreateModalOpen] = useState(false);
  const [deleteModalOpen, setDeleteModalOpen] = useState(false);
  const [selectedProfile, setSelectedProfile] = useState<Profile | null>(null);

  const [newProfileName, setNewProfileName] = useState('');
  const [newProfileDescription, setNewProfileDescription] = useState('');
  const [selectedTemplate, setSelectedTemplate] = useState<
    'blank' | 'simple_remap' | 'capslock_escape' | 'vim_navigation' | 'gaming'
  >('blank');
  const [nameError, setNameError] = useState('');
  const [activationError, setActivationError] = useState<string | null>(null);
  const [activationSuccess, setActivationSuccess] = useState<string | null>(
    null
  );
  const [autoGenerateNotification, setAutoGenerateNotification] = useState<
    string | null
  >(null);
  const [autoGenerateError, setAutoGenerateError] = useState<string | null>(
    null
  );
  const [isAutoGenerating, setIsAutoGenerating] = useState(false);
  const hasAttemptedAutoGenerate = useRef(false);

  // Auto-generate default profile on first load if no profiles exist
  useEffect(() => {
    // Only run once when profiles data is loaded successfully (no error)
    if (
      !isLoading &&
      !error &&
      !hasAttemptedAutoGenerate.current &&
      profiles.length === 0
    ) {
      hasAttemptedAutoGenerate.current = true;
      handleAutoGenerateDefaultProfile();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isLoading, error, profiles.length]);

  const handleAutoGenerateDefaultProfile = async () => {
    setIsAutoGenerating(true);
    setAutoGenerateError(null);

    try {
      // Create default profile with blank template
      await createProfileMutation.mutateAsync({
        name: 'default',
        template: 'blank',
      });

      // Activate the newly created profile
      await activateProfileMutation.mutateAsync('default');

      // Show success notification
      setAutoGenerateNotification(
        'Default profile created. Click "Edit" to customize.'
      );

      // Auto-dismiss notification after 5 seconds
      setTimeout(() => {
        setAutoGenerateNotification(null);
      }, 5000);
    } catch (err) {
      // Handle failure gracefully
      const errorMessage = getErrorMessage(
        err,
        'Failed to create default profile'
      );

      // Check if it's a daemon offline error
      if (
        errorMessage.includes('Failed to fetch') ||
        errorMessage.includes('NetworkError')
      ) {
        setAutoGenerateError(
          'Unable to connect to daemon. Please ensure the daemon is running and try again.'
        );
      } else {
        setAutoGenerateError(errorMessage);
      }

      console.error('Auto-generate default profile failed:', err);
    } finally {
      setIsAutoGenerating(false);
    }
  };

  const handleRetryAutoGenerate = () => {
    handleAutoGenerateDefaultProfile();
  };

  const validateProfileName = (name: string): boolean => {
    if (!name.trim()) {
      setNameError('Profile name is required');
      return false;
    }
    if (name.length > 50) {
      setNameError('Profile name must be 50 characters or less');
      return false;
    }
    if (profiles.some((p) => p.name === name && p.id !== selectedProfile?.id)) {
      setNameError('Profile name already exists');
      return false;
    }
    setNameError('');
    return true;
  };

  const handleCreateProfile = async () => {
    if (!validateProfileName(newProfileName)) return;

    try {
      await createProfileMutation.mutateAsync({
        name: newProfileName,
        template: selectedTemplate,
      });

      setCreateModalOpen(false);
      setNewProfileName('');
      setNewProfileDescription('');
      setSelectedTemplate('blank'); // Reset to default
      setNameError('');
    } catch (err) {
      setNameError(getErrorMessage(err, 'Failed to create profile'));
    }
  };

  const handleActivateProfile = async (profileId: string) => {
    // Prevent rapid activation - wait for previous to complete
    if (activateProfileMutation.isPending) {
      return;
    }

    // Clear any previous activation errors and success messages
    setActivationError(null);
    setActivationSuccess(null);

    try {
      const result = await activateProfileMutation.mutateAsync(profileId);

      // Check for compilation errors in the result
      if (result.errors && result.errors.length > 0) {
        const errorMessage = result.errors.join('\n');
        setActivationError(`Compilation failed:\n${errorMessage}`);
        console.error('Compilation errors:', result.errors);
      } else {
        // Show success notification - daemon auto-restarts so profile is immediately applied
        setActivationSuccess(`Profile '${profileId}' applied!`);

        // Auto-dismiss after 3 seconds (shorter since no action needed)
        setTimeout(() => {
          setActivationSuccess(null);
        }, 3000);
      }
    } catch (err) {
      // Handle API errors
      const errorMessage = getErrorMessage(err, 'Unknown error occurred');
      setActivationError(`Failed to activate profile: ${errorMessage}`);
      console.error('Failed to activate profile:', err);
    }
  };

  const handleNavigateToConfig = (profileName: string) => {
    navigate(`/profiles/${profileName}/config`);
  };

  const handleUpdateProfileName = async (
    originalName: string,
    newName: string
  ) => {
    if (!newName.trim()) return;
    if (newName === originalName) return;

    // Validate name
    if (profiles.some((p) => p.name === newName && p.name !== originalName)) {
      console.error('Profile name already exists');
      return;
    }

    try {
      await updateProfileMutation.mutateAsync({
        originalName,
        updates: { name: newName },
      });
    } catch (err) {
      console.error('Failed to update profile name:', err);
    }
  };

  const handleUpdateProfileDescription = async (
    profileName: string,
    newDescription: string
  ) => {
    try {
      await updateProfileMutation.mutateAsync({
        originalName: profileName,
        updates: { description: newDescription },
      });
    } catch (err) {
      console.error('Failed to update profile description:', err);
    }
  };

  const handleDeleteProfile = (profile: Profile) => {
    setSelectedProfile(profile);
    setDeleteModalOpen(true);
  };

  const handleConfirmDelete = async () => {
    if (!selectedProfile) return;

    try {
      await deleteProfileMutation.mutateAsync(selectedProfile.name);
      setDeleteModalOpen(false);
      setSelectedProfile(null);
    } catch (err) {
      console.error('Failed to delete profile:', err);
      // Show error to user (could add error state here)
    }
  };

  const handleCancelCreate = () => {
    setCreateModalOpen(false);
    setNewProfileName('');
    setNewProfileDescription('');
    setSelectedTemplate('blank');
    setNameError('');
  };

  // Show loading state while fetching
  if (isLoading) {
    return (
      <div className="flex flex-col gap-4 md:gap-6 p-4 md:p-6 lg:p-8">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <SkeletonCard className="h-8 w-32" />
          <SkeletonCard className="h-10 w-40" />
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-6">
          <SkeletonCard />
          <SkeletonCard />
          <SkeletonCard />
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-4 md:gap-6 p-4 md:p-6 lg:p-8">
      {/* Error Display */}
      {error && (
        <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-lg">
          <p className="text-sm text-red-400">
            Failed to load profiles:{' '}
            {error instanceof Error ? error.message : 'Unknown error'}
          </p>
        </div>
      )}

      {/* Activation Error Display */}
      {activationError && (
        <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-lg">
          <div className="flex justify-between items-start">
            <div className="flex-1">
              <p className="text-sm font-semibold text-red-400 mb-2">
                Profile Activation Error
              </p>
              <pre className="text-xs text-red-300 whitespace-pre-wrap font-mono">
                {activationError}
              </pre>
            </div>
            <button
              onClick={() => setActivationError(null)}
              className="text-red-400 hover:text-red-300 ml-4"
              aria-label="Dismiss error"
            >
              ×
            </button>
          </div>
        </div>
      )}

      {/* Activation Success Notification - Fixed position toast */}
      {activationSuccess && (
        <div className="fixed top-4 right-4 z-50 p-4 bg-green-600 border border-green-500 rounded-lg shadow-lg animate-in fade-in slide-in-from-top-2 duration-300 max-w-sm">
          <div className="flex items-start gap-3">
            <CheckCircle
              size={20}
              className="text-white flex-shrink-0 mt-0.5"
              aria-hidden="true"
            />
            <div className="flex-1">
              <p className="text-sm text-white font-medium">
                {activationSuccess}
              </p>
            </div>
            <button
              onClick={() => setActivationSuccess(null)}
              className="text-white/70 hover:text-white ml-2"
              aria-label="Dismiss notification"
            >
              ×
            </button>
          </div>
        </div>
      )}

      {/* Auto-Generate Success Notification - Fixed position toast */}
      {autoGenerateNotification && (
        <div className="fixed top-4 right-4 z-50 p-4 bg-green-600 border border-green-500 rounded-lg shadow-lg animate-in fade-in slide-in-from-top-2 duration-300 max-w-sm">
          <div className="flex items-start gap-3">
            <CheckCircle
              size={20}
              className="text-white flex-shrink-0 mt-0.5"
              aria-hidden="true"
            />
            <div className="flex-1">
              <p className="text-sm text-white font-medium">
                {autoGenerateNotification}
              </p>
            </div>
            <button
              onClick={() => setAutoGenerateNotification(null)}
              className="text-white/70 hover:text-white ml-2"
              aria-label="Dismiss notification"
            >
              ×
            </button>
          </div>
        </div>
      )}

      {/* Auto-Generate Error Display */}
      {autoGenerateError && (
        <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-lg">
          <div className="flex items-start gap-3">
            <AlertCircle
              size={20}
              className="text-red-400 flex-shrink-0 mt-0.5"
              aria-hidden="true"
            />
            <div className="flex-1">
              <p className="text-sm font-semibold text-red-400 mb-2">
                Failed to Create Default Profile
              </p>
              <p className="text-sm text-red-300 mb-3">{autoGenerateError}</p>
              <Button
                variant="secondary"
                size="sm"
                onClick={handleRetryAutoGenerate}
                disabled={isAutoGenerating}
                aria-label="Retry creating default profile"
              >
                {isAutoGenerating ? 'Retrying...' : 'Retry'}
              </Button>
            </div>
            <button
              onClick={() => setAutoGenerateError(null)}
              className="text-red-400 hover:text-red-300 ml-2"
              aria-label="Dismiss error"
            >
              ×
            </button>
          </div>
        </div>
      )}

      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <h1 className="text-xl md:text-2xl lg:text-3xl font-semibold text-slate-100">
          Profiles
        </h1>
        <Button
          variant="primary"
          size="md"
          onClick={() => setCreateModalOpen(true)}
          aria-label="Create new profile"
          className="w-full sm:w-auto min-h-[44px] sm:min-h-0"
        >
          <Plus size={20} className="mr-2" aria-hidden="true" />
          Create Profile
        </Button>
      </div>

      {/* Profile Grid - responsive: 1 col mobile, 2 cols tablet, 3 cols desktop */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-6">
        {profiles.map((profile) => (
          <ProfileCard
            key={profile.id}
            name={profile.name}
            description={profile.description}
            isActive={profile.isActive}
            isActivating={activateProfileMutation.isPending}
            lastModified={profile.lastModified}
            rhaiPath={profile.rhaiPath}
            fileExists={profile.fileExists}
            onActivate={() => handleActivateProfile(profile.id)}
            onDelete={() => handleDeleteProfile(profile)}
            onPathClick={() => handleNavigateToConfig(profile.name)}
            onUpdateName={(newName) =>
              handleUpdateProfileName(profile.name, newName)
            }
            onUpdateDescription={(newDesc) =>
              handleUpdateProfileDescription(profile.name, newDesc)
            }
          />
        ))}
      </div>

      {/* Create Profile Modal */}
      <Modal
        open={createModalOpen}
        onClose={handleCancelCreate}
        title="Create New Profile"
      >
        <div className="flex flex-col gap-md">
          <Input
            type="text"
            value={newProfileName}
            onChange={(value) => {
              setNewProfileName(value);
              if (nameError) validateProfileName(value);
            }}
            aria-label="Profile name"
            placeholder="Profile name"
            error={nameError}
            maxLength={50}
          />

          {/* Template Selector */}
          <div className="flex flex-col gap-2">
            <label
              htmlFor="template-select"
              className="text-sm font-medium text-slate-300"
            >
              Starting Template
            </label>
            <select
              id="template-select"
              value={selectedTemplate}
              onChange={(e) =>
                setSelectedTemplate(e.target.value as typeof selectedTemplate)
              }
              className="w-full px-3 py-2 bg-slate-800 border border-slate-700 rounded-md text-slate-100 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              aria-label="Select profile template"
            >
              <option value="blank">Blank - Empty configuration</option>
              <option value="simple_remap">
                Simple Remap - Basic key remapping examples
              </option>
              <option value="capslock_escape">
                CapsLock→Escape - CapsLock as Escape key
              </option>
              <option value="vim_navigation">
                Vim Navigation - HJKL arrow keys layer
              </option>
              <option value="gaming">Gaming - Optimized for gaming</option>
            </select>
            <p className="text-xs text-slate-400">
              Choose a starting template for your profile configuration
            </p>
          </div>

          <Input
            type="text"
            value={newProfileDescription}
            onChange={(value) => setNewProfileDescription(value)}
            aria-label="Profile description"
            placeholder="Description (optional)"
            maxLength={200}
          />
          <div className="flex gap-2 justify-end mt-2">
            <Button
              variant="secondary"
              size="md"
              onClick={handleCancelCreate}
              aria-label="Cancel creating profile"
            >
              Cancel
            </Button>
            <Button
              variant="primary"
              size="md"
              onClick={handleCreateProfile}
              aria-label="Save new profile"
            >
              Create
            </Button>
          </div>
        </div>
      </Modal>

      {/* Delete Confirmation Modal */}
      <Modal
        open={deleteModalOpen}
        onClose={() => setDeleteModalOpen(false)}
        title="Delete Profile"
      >
        <div className="flex flex-col gap-md">
          <p className="text-slate-300">
            Are you sure you want to delete the profile{' '}
            <strong className="text-white">{selectedProfile?.name}</strong>?
            This action cannot be undone.
          </p>
          <div className="flex gap-2 justify-end mt-2">
            <Button
              variant="secondary"
              size="md"
              onClick={() => setDeleteModalOpen(false)}
              aria-label="Cancel deleting profile"
            >
              Cancel
            </Button>
            <Button
              variant="danger"
              size="md"
              onClick={handleConfirmDelete}
              aria-label="Confirm delete profile"
            >
              Delete
            </Button>
          </div>
        </div>
      </Modal>
    </div>
  );
};

export default ProfilesPage;
